load("power.RData")
png("plot3.png")
plot(power$Datetime, power$Sub_metering_1, type = "s", xlab = "",ylab = "Energy sub metering")
lines(power$Datetime, power$Sub_metering_2,type = "s", col = "red")
lines(power$Datetime, power$Sub_metering_3,type = "s", col = "blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = c(1,1,1),col = c("black","red","blue"))
dev.off()
